"use client";

/**
 * ChatModelDemo — interactive message builder for Chat Models.
 *
 * Shows the three message types (SystemMessage, HumanMessage, AIMessage)
 * and lets the user compose a conversation, then "invoke" the model
 * to see what the Python code would look like.
 */

import { useState } from "react";

const MSG_TYPES = [
  { type: "system",  label: "SystemMessage", color: "#a78bfa", icon: "⚙️",  placeholder: "You are a helpful RAG expert…" },
  { type: "human",   label: "HumanMessage",  color: "#60a5fa", icon: "👤", placeholder: "What is cosine similarity?" },
  { type: "ai",      label: "AIMessage",     color: "#10b981", icon: "🤖", placeholder: "(Generated by the LLM — not entered manually)" },
];

const PRESETS = [
  {
    label: "Basic Q&A",
    messages: [
      { type: "system",  text: "You are a concise ML tutor. Explain concepts clearly." },
      { type: "human",   text: "What is a vector embedding?" },
    ],
  },
  {
    label: "RAG Grounding",
    messages: [
      { type: "system",  text: "Answer ONLY using the provided context. If not in context, say so." },
      { type: "human",   text: "What did the lecture say about chunk overlap?" },
    ],
  },
  {
    label: "Multi-turn",
    messages: [
      { type: "system",  text: "You are a LangChain tutor." },
      { type: "human",   text: "What is LCEL?" },
      { type: "ai",      text: "LCEL stands for LangChain Expression Language. It uses the | operator to chain components." },
      { type: "human",   text: "Can you show me a quick example?" },
    ],
  },
];

const PROVIDERS = [
  { id: "openai",    label: "OpenAI",    import: "from langchain_openai import ChatOpenAI",       model: "gpt-4o-mini" },
  { id: "anthropic", label: "Anthropic", import: "from langchain_anthropic import ChatAnthropic",  model: "claude-3-5-haiku-20241022" },
  { id: "ollama",    label: "Ollama",    import: "from langchain_ollama import ChatOllama",         model: "llama3.2" },
];

function buildCode(provider, messages) {
  const p = PROVIDERS.find(x => x.id === provider);
  const msgLines = messages.map(m => {
    if (m.type === "system") return `  SystemMessage(content="${m.text}"),`;
    if (m.type === "human")  return `  HumanMessage(content="${m.text}"),`;
    return `  AIMessage(content="${m.text}"),`;
  }).join("\n");

  return `${p.import}
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage

model = ${p.id === "openai" ? "ChatOpenAI" : p.id === "anthropic" ? "ChatAnthropic" : "ChatOllama"}(model="${p.model}")

messages = [
${msgLines}
]

response = model.invoke(messages)
print(response.content)          # plain text answer
print(response.response_metadata) # token counts, finish reason`;
}

export default function ChatModelDemo() {
  const [messages, setMessages]   = useState(PRESETS[0].messages);
  const [provider, setProvider]   = useState("openai");
  const [newType, setNewType]     = useState("human");
  const [newText, setNewText]     = useState("");
  const [showCode, setShowCode]   = useState(false);

  const addMessage = () => {
    if (!newText.trim()) return;
    setMessages([...messages, { type: newType, text: newText.trim() }]);
    setNewText("");
  };

  const removeMessage = (i) => setMessages(messages.filter((_, idx) => idx !== i));

  const loadPreset = (preset) => {
    setMessages(preset.messages);
    setShowCode(false);
  };

  const code = buildCode(provider, messages);

  return (
    <div style={{ fontFamily: "var(--font-body)" }}>
      <p style={{ fontSize: "0.85rem", color: "var(--text-secondary)", margin: "0 0 1.25rem" }}>
        Chat Models use <strong style={{ color: "var(--text-primary)" }}>structured message lists</strong> instead
        of raw strings. Build a conversation below, choose your provider, and see the exact Python code.
        LangChain&apos;s abstraction means swapping providers requires changing{" "}
        <strong style={{ color: "var(--text-primary)" }}>one import line</strong>.
      </p>

      {/* Presets + Provider */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: "0.75rem", marginBottom: "1rem" }}>
        <div style={{ display: "flex", gap: "0.4rem", flexWrap: "wrap" }}>
          {PRESETS.map(p => (
            <button key={p.label} onClick={() => loadPreset(p)} style={{
              padding: "0.3rem 0.7rem",
              borderRadius: "99px",
              border: "1px solid var(--glass-border)",
              background: "var(--bg-tertiary)",
              color: "var(--text-secondary)",
              fontSize: "0.78rem",
              cursor: "pointer",
            }}>
              {p.label}
            </button>
          ))}
        </div>
        <div style={{ display: "flex", gap: "0.4rem" }}>
          {PROVIDERS.map(p => (
            <button key={p.id} onClick={() => setProvider(p.id)} style={{
              padding: "0.3rem 0.7rem",
              borderRadius: "99px",
              border: `1px solid ${provider === p.id ? "#6366f1" : "var(--glass-border)"}`,
              background: provider === p.id ? "rgba(99,102,241,0.15)" : "var(--bg-tertiary)",
              color: provider === p.id ? "#a78bfa" : "var(--text-secondary)",
              fontSize: "0.78rem",
              cursor: "pointer",
              fontWeight: provider === p.id ? 600 : 400,
            }}>
              {p.label}
            </button>
          ))}
        </div>
      </div>

      {/* Message list */}
      <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem", marginBottom: "1rem" }}>
        {messages.map((msg, i) => {
          const mt = MSG_TYPES.find(t => t.type === msg.type);
          return (
            <div key={i} style={{
              display: "flex",
              alignItems: "flex-start",
              gap: "0.6rem",
              padding: "0.625rem 0.875rem",
              borderRadius: "var(--radius-sm)",
              background: `${mt.color}11`,
              border: `1px solid ${mt.color}33`,
              borderLeft: `3px solid ${mt.color}`,
            }}>
              <span style={{ fontSize: "0.9rem", flexShrink: 0, lineHeight: "1.5" }}>{mt.icon}</span>
              <div style={{ flex: 1 }}>
                <span style={{ fontSize: "0.7rem", fontWeight: 700, color: mt.color, textTransform: "uppercase", letterSpacing: "0.06em" }}>
                  {mt.label}
                </span>
                <p style={{ margin: "0.15rem 0 0", fontSize: "0.875rem", color: "var(--text-secondary)", lineHeight: 1.5 }}>
                  {msg.text}
                </p>
              </div>
              {msg.type !== "ai" && (
                <button onClick={() => removeMessage(i)} style={{
                  background: "none", border: "none", color: "var(--text-tertiary)", cursor: "pointer",
                  fontSize: "0.85rem", flexShrink: 0, lineHeight: 1, padding: "0.15rem",
                }}>✕</button>
              )}
            </div>
          );
        })}
      </div>

      {/* Add message */}
      <div style={{ display: "flex", gap: "0.5rem", marginBottom: "1rem" }}>
        <select value={newType} onChange={e => setNewType(e.target.value)} style={{
          padding: "0.5rem 0.625rem",
          borderRadius: "var(--radius-sm)",
          border: "1px solid var(--glass-border)",
          background: "var(--bg-tertiary)",
          color: "var(--text-secondary)",
          fontSize: "0.82rem",
          flexShrink: 0,
        }}>
          {MSG_TYPES.filter(t => t.type !== "ai").map(t => (
            <option key={t.type} value={t.type}>{t.label}</option>
          ))}
        </select>
        <input
          value={newText}
          onChange={e => setNewText(e.target.value)}
          onKeyDown={e => e.key === "Enter" && addMessage()}
          placeholder={MSG_TYPES.find(t => t.type === newType)?.placeholder}
          style={{
            flex: 1,
            padding: "0.5rem 0.75rem",
            borderRadius: "var(--radius-sm)",
            border: "1px solid var(--glass-border)",
            background: "var(--bg-tertiary)",
            color: "var(--text-primary)",
            fontSize: "0.875rem",
          }}
        />
        <button onClick={addMessage} style={{
          padding: "0.5rem 1rem",
          borderRadius: "var(--radius-sm)",
          border: "none",
          background: "#6366f1",
          color: "white",
          fontWeight: 700,
          fontSize: "0.875rem",
          cursor: "pointer",
          flexShrink: 0,
        }}>+ Add</button>
      </div>

      {/* Code toggle */}
      <button onClick={() => setShowCode(!showCode)} style={{
        padding: "0.5rem 1rem",
        borderRadius: "var(--radius-sm)",
        border: "1px solid rgba(99,102,241,0.35)",
        background: showCode ? "rgba(99,102,241,0.15)" : "var(--bg-tertiary)",
        color: "#a78bfa",
        fontWeight: 600,
        fontSize: "0.875rem",
        cursor: "pointer",
        marginBottom: "0.75rem",
      }}>
        {showCode ? "▼ Hide" : "▶ Show"} Python code
      </button>

      {showCode && (
        <pre style={{
          fontFamily: "var(--font-mono)",
          fontSize: "0.82rem",
          background: "#0a0f1e",
          border: "1px solid var(--glass-border)",
          borderRadius: "var(--radius-sm)",
          padding: "1rem",
          overflowX: "auto",
          color: "#c4b5fd",
          margin: 0,
        }}>
          {code}
        </pre>
      )}
    </div>
  );
}
